[package]

name = "urlencoded"
version = "0.1.0"
authors = ["Patrick Tran <patrick.tran06@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>",
           "Michael Sproul <micsproul@gmail.com>"]

[dependencies]
iron = "*"
url = "*"
plugin = "*"

